# data = open("newfile.txt", "x")
# data = open("newfile.txt", "w")
# data.write("this now has some content that is useful to us")
# data= open("newfile.txt","r")
# print(data.read())
data = open("newfile.txt", "a")
data.write("now there is more content in this file and it did not go away")
data= open("newfile.txt","r")
print(data.read())
